<?php

namespace Helpers;

require_once dirname(__FILE__) . '/../Loader.php';
$loader = new \Helpers\Loader(array('../'));
$loader->register();

/**
 * Test class for ArrayUtil.
 * Generated by PHPUnit on 2013-02-24 at 03:02:46.
 */
class ArrayUtilTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var ArrayUtil
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new \Helpers\ArrayUtil;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testRemoveItemByValue().
	 */
	public function testRemoveItemByValue()
	{
		$this->assertEquals(1,count($this->object->removeItemByValue(2, array(2, 3))));
	}

	/**
	 * @covers {ArrayUtil}::{origMethodName}
	 */
	public function testVerificaTipo()
	{
		$this->assertInstanceOf('\Helpers\ArrayUtil', $this->object);
	}

}

?>
