<?php

namespace helpers;

require_once dirname(__FILE__) . '/../Loader.php';

$loader = new \helpers\Loader(array('../../'));
$loader->register();

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-11 at 04:21:34.
 */
class DateTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Date;
    }

  

    /**
     * @covers Helpers\Date::getDateToMysql
     * @todo   Implement testGetDateToMysql().
     */
    public function testGetDateToMysql() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Helpers\Date::isValidDate
     * @todo   Implement isValidDate().
     */
    public function testIsValidDate() {
        $v1 = Date::isValidDate('2014-02-01');
        $this->assertInstanceOf('Datetime', $v1);
        
        $v1 = Date::isValidDate('22-02-2014');
        $this->assertInstanceOf('Datetime', $v1);
        
        $v1 = Date::isValidDate('02/22/2014');
        $this->assertInstanceOf('Datetime', $v1);
        
        $v2 = Date::isValidDate('22/02/2014');
        $this->assertEquals(false, $v2);
    }

    /**
     * @covers Helpers\Date::getDayWeek
     * @todo   Implement testGetDayWeek().
     */
    public function testGetDayWeek() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Helpers\Date::compareDateDiff
     * @todo   Implement testCompareDateDiff().
     */
    public function testCompareDateDiff() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Helpers\Date::getBrFormat
     * @todo   Implement testGetBrFormat().
     */
    public function testGetBrFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
