<?php
require_once dirname(__FILE__) . '/../Loader.php';

$loader = new \helpers\Loader(array('../'));
$loader->register();

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-24 at 00:01:37.
 */
class SecureSessionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SecureSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SecureSession;
        
        session_save_path('./session/');
        session_start();
        if (empty($_SESSION['time'])) {
            $_SESSION['test'] = 'é um teste';
        } 
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SecureSession::open
     * @todo   Implement testOpen().
     */
    public function testOpen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecureSession::close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecureSession::read
     * @todo   Implement testRead().
     */
    public function testRead() {
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        //faltou extensão mcrypt
        //$this->assertEquals('é um teste', $this->object->read('test'));
    }

    /**
     * @covers SecureSession::write
     * @todo   Implement testWrite().
     */
    public function testWrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecureSession::destroy
     * @todo   Implement testDestroy().
     */
    public function testDestroy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecureSession::gc
     * @todo   Implement testGc().
     */
    public function testGc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
