<?php

namespace helpers;

require_once dirname(__FILE__) . '/../Loader.php';

$loader = new \helpers\Loader(array('../../'));
$loader->register();

/**
 * Test class for Cache.
 * Generated by PHPUnit on 2013-02-24 at 19:38:37.
 */
class CacheFileTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var CacheFile
	 */
	protected $object;
	protected $key;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new CacheFile(60,'./');
		$this->key = 'teste';
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetPathFileName().
	 */
	public function testGetPathFileName()
	{
		$return = $this->object->getPathFileName($this->key);
		$this->assertEquals(true, is_string($return));
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testIsCache().
	 */
	public function testIsCache()
	{
		$this->assertInternalType('bool', $this->object->isCache($this->key));
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testWrite().
	 */
	public function testWrite()
	{
		$this->assertEquals(true, $this->object->write($this->key,'teste'));
	}

	/**
	 * @depends testWrite
	 */
	public function testRead()
	{
		try {
			$this->object->read($this->key);
		} catch (Exception $exc) {
			$this->fail($exc->getTraceAsString());
		}
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testClearAllCache().
	 */
	public function testClearAllCache()
	{
		
	}

}

?>
